"""
Generate action horizon comparison plot from evaluation results.

This script reads a pickle file containing evaluation results (generated by
evaluation.py) and creates a publication-quality plot showing success rate
vs action horizon with confidence intervals.

Usage:
    python make_action_horizon_comparison_fig.py [results_file.pkl]

If no argument is provided, defaults to "evaluation_results.pkl"
"""

import sys
from pathlib import Path
from typing import List

import dill
import matplotlib.pyplot as plt
import numpy as np
import statsmodels.stats.proportion as smp

# Import plotting utilities from evaluation script
from evaluation import HorizonResult
from matplotlib.figure import Figure


def make_action_horizon_plot(
    results: List[HorizonResult], plot_name: str = "Action Horizon Comparison", dpi: int = 150
) -> Figure:
    """Create plot showing success rate vs action horizon with checkpoint labels."""
    # Plotting style constants
    NAVY = "#1f3a68"
    GRID_COLOR = "#e0e0e0"

    def compute_wilson_ci(success_rates: np.ndarray, num_trials: np.ndarray) -> np.ndarray:
        """Compute Wilson 95% confidence intervals and return as yerr format."""
        ci_bounds = np.array(
            [
                smp.proportion_confint(int(p * n), n, alpha=0.05, method="wilson")
                for p, n in zip(success_rates, num_trials)
            ],
            dtype=float,
        )
        ci_lo = ci_bounds[:, 0]
        ci_hi = ci_bounds[:, 1]
        # Return distances from central value for error bars
        return np.vstack([np.clip(success_rates - ci_lo, 0, 1), np.clip(ci_hi - success_rates, 0, 1)])

    fig, ax = plt.subplots(figsize=(5.0, 4.0))
    ax.set_facecolor("white")

    if not results:
        print("Warning: No results to plot.")
        return fig

    # Sort by horizon
    results = sorted(results, key=lambda r: r.horizon)

    horizons = np.array([res.horizon for res in results], dtype=float)
    success_rates = np.array([res.success_rate for res in results], dtype=float)
    num_trials = np.array([res.num_trials for res in results], dtype=int)

    # Compute error bars
    yerr = compute_wilson_ci(success_rates, num_trials)

    # Main line with markers
    ax.plot(
        horizons,
        success_rates,
        color=NAVY,
        linewidth=1.5,
        marker="o",
        markersize=4,
        markeredgecolor="white",
        markeredgewidth=0.8,
        zorder=3,
    )

    # Error bars with 95% Wilson CI
    ax.errorbar(
        horizons,
        success_rates,
        yerr=yerr,
        fmt="none",
        ecolor=NAVY,
        elinewidth=1.0,
        capsize=4.0,
        capthick=1.0,
        alpha=0.9,
        zorder=2,
    )

    # Add checkpoint labels for each point
    for res in results:
        # Extract checkpoint name from path (e.g., "epoch=075-val_loss=0.1215...")
        ckpt_path = Path(res.checkpoint_path)
        ckpt_name = ckpt_path.stem if ckpt_path.suffix == ".ckpt" else ckpt_path.name

        # Truncate checkpoint name to first 10 chars for readability
        label_text = ckpt_name[:10] + "..." if len(ckpt_name) > 10 else ckpt_name

        # Position label slightly above the data point
        ax.annotate(
            label_text,
            xy=(res.horizon, res.success_rate),
            xytext=(0, 5),  # 5 points above
            textcoords="offset points",
            fontsize=6,
            color=NAVY,
            ha="center",
            va="bottom",
            alpha=0.8,
        )

    ax.set_xticks(horizons)
    ax.set_xticklabels([str(int(val)) if float(val).is_integer() else f"{val:g}" for val in horizons])
    ax.set_yticks(np.linspace(0, 1.0, 6))
    ax.set_title(plot_name, fontsize=12, fontweight="bold", pad=10)
    ax.set_xlabel("Action Horizon (steps)", fontsize=12)
    ax.set_ylabel("Success Rate", fontsize=12)
    ax.grid(True, which="major", color=GRID_COLOR, linestyle="-", linewidth=0.8, alpha=0.6)

    for spine in ax.spines.values():
        spine.set_linewidth(1.0)
        spine.set_color("#4f4f4f")

    ax.tick_params(axis="both", which="major", labelsize=8, length=6, width=1)

    fig.tight_layout()
    fig.set_dpi(dpi)

    return fig


def main():
    # Get pickle file path from command line or use default
    if len(sys.argv) > 1:
        results_file = sys.argv[1]
    else:
        results_file = "evaluation_results.pkl"

    results_path = Path(results_file)
    if not results_path.exists():
        raise FileNotFoundError(f"Results file not found: {results_file}")

    print(f"Loading results from: {results_file}")

    # Load evaluation results
    with open(results_path, "rb") as f:
        results_data = dill.load(f)

    best_results = results_data["best_results"]
    config = results_data.get("config", {})

    # Print summary
    print(f"\n{'=' * 60}")
    print("Loaded Evaluation Results")
    print(f"{'=' * 60}")
    print(f"Environment: {config.get('env_id', 'N/A')}")
    print(f"Trials per horizon: {config.get('num_trials_per_horizon', 'N/A')}")
    print(f"Number of horizons: {len(best_results)}")
    print(f"{'=' * 60}")
    print(f"{'Horizon':<10} {'Success Rate':<15} {'Successes':<15} {'Checkpoint'}")
    print("-" * 60)
    for res in best_results:
        print(
            f"{res.horizon:<10} {res.success_rate:.2%}{'':<10} "
            f"{res.num_successes}/{res.num_trials}{'':<8} {res.checkpoint_name[:40]}"
        )
    print(f"{'=' * 60}")

    # Create and save plot
    print("\nGenerating plot...")
    fig = make_action_horizon_plot(best_results, plot_name="Success Rate vs Action Horizon (Best Checkpoints)", dpi=150)

    # Save with timestamp-based name to avoid overwriting
    output_path = "success_rate_vs_action_horizon.png"
    fig.savefig(output_path, dpi=150, bbox_inches="tight")
    print(f"Plot saved to: {output_path}")

    # Show plot
    plt.show()

    print("\nDone!")


if __name__ == "__main__":
    main()
